### ISSUE TITLE
Error Android Termux

### ISSUE THREAD

**Issue by scriptxd** [jfadev/bottok#1]
check Screenshot 
![Screenshot_2023_0303_155723](https://user-images.githubusercontent.com/104721718/222690493-c3d5b5e7-4bee-46fd-b4f5-e9892ae31522.jpg)

wget https://github.com/jfadev/bottok/archive/refs/tags/v1.0.0.zip
After Download This Zip 
This command not working error no such file $ unzip master.zip bottok 

So i download it via git clone https://github.com/jfadev/bottok

Then cd bottok & npm install after that i got this error...

**Comment by jfadev** [comment]
Doc fixed! https://github.com/jfadev/bottok/commit/453bf494c78e162570f9aeb1010e65f4b5e511ae
