### ISSUE TITLE
Captcha rendering error horizontal black stripes

### ISSUE THREAD

**Issue by jfadev** [jfadev/bottok#12]
related to this image-terminal issue https://github.com/sindresorhus/terminal-image/issues/45
![Captura desde 2023-03-29 17-47-13](https://user-images.githubusercontent.com/46567106/228690616-189b76ff-3889-4823-8b8b-d6423abdb023.png)

**Comment by Victor608-jpg** [comment]
what is the captcha word in windows?
![captcha](https://github.com/jfadev/bottok/assets/143277828/de4a49e6-4b46-49b1-9e5a-a29745cd7bf7)
I put this and its incorrect

**Comment by jfadev** [comment]
Starting with v1.0.9, the captcha in the terminal is optional.
