### ISSUE TITLE
Bro termux dont work

### ISSUE THREAD

**Issue by Kindokenzo** [jfadev/bottok#18]
![Screenshot_2023-06-24-17-25-29-53_84d3000e3f4017145260f7618db1d683](https://github.com/jfadev/bottok/assets/112830018/a5b55767-e4c4-4639-91bd-7a3a0b3ea1cd)
localhost:~/bottok# proot-distro login alpine

Error: proot-distro should not be executed as root user.

**Comment by jfadev** [comment]
It seems that you are using an outdated version of Termux. You need to download it F-Droid or Termux official GitHub
