### ISSUE TITLE
Bro fix this

### ISSUE THREAD

**Issue by scriptxd** [jfadev/bottok#3]
Increase views limit only please, only 5 k after that cookies expired quickly

**Comment by scriptxd** [comment]
After 4/5 submiit xefoy given only 1 view

**Comment by scriptxd** [comment]
Givee one key 😊❤️

**Comment by jfadev** [comment]
Click on the link add Bot Tok to cart, add the coupon, proceed and receive a key by email.

**Comment by scriptxd** [comment]
Successfully purchased.... 
Thanks Brother.... ❤️
God Bless U...❤️
