### ISSUE TITLE
Captcha issue

### ISSUE THREAD

**Issue by gooeyglobs** [jfadev/bottok#31]
The Captcha just says "view the security of", And when I input that, it just puts up "view the security of" again.

**Comment by gooeyglobs** [comment]
![view](https://github.com/jfadev/bottok/assets/101294388/fedaaaa7-3fe0-4556-a82e-7dfa72f2e71b)

**Comment by gooeyglobs** [comment]
it was working perfectly a couple days ago

**Comment by jfadev** [comment]
The site that BotTok automates have activated an anti-bot protection based on Cloudflare. We are working on a bypass to resolve the issue. Join the Telegram group to stay informed of the news. https://t.me/bottok_help

**Comment by jfadev** [comment]
Same issue as https://github.com/jfadev/bottok/issues/33
