### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by exmachina222** [jfadev/bottok#32]
How to fix this?
![Annotation 2023-08-05 011449](https://github.com/jfadev/bottok/assets/141142459/08bf61f8-f1a5-408c-8697-9778f543bc40)

**Comment by jfadev** [comment]
The site that BotTok automates have activated an anti-bot protection based on Cloudflare. We are working on a bypass to resolve the issue. Join the Telegram group to stay informed of the news. https://t.me/bottok_help

**Comment by jfadev** [comment]
Same issue as https://github.com/jfadev/bottok/issues/33
