### ISSUE TITLE
capcha issue

### ISSUE THREAD

**Issue by jimmyinnit69** [jfadev/bottok#33]
view the security of please fix!

**Comment by jfadev** [comment]
The site that BotTok automates have activated an anti-bot protection based on Cloudflare. We are working on a bypass to resolve the issue. Join the Telegram group to stay informed of the news. https://t.me/bottok_help

**Comment by medaminnne** [comment]
the issue was resloved ???

**Comment by jfadev** [comment]
A few days ago, Zefoy.com activated the "Under attack mode" on its platform (enter zefoy.com and you will understand what we are talking about). This has made BotTok unable to enter zefoy.com normally, is detected as a bot. This manifests itself with the captcha "view the security of" or that it does not go beyond the Tasks screen or that it goes through the "Solve captcha automatically" screen.  The new version of BotTok (1.0.8) is not able to bypass this protection using BotTok as normal, The only way is to use the method I post in the video (in Telegram) with the new -r flag, take control of a real browser and pass the CF protection, after this a file will be created cookies.json that will make BotTok work normally for the duration of the session. I know it's not easy or comfortable, but for now it's the only way.

**Comment by jfadev** [comment]
We have posted the method to bypass Cloudflare in the Telegram group (https://t.me/bottok_help)
