### ISSUE TITLE
Any solutions?

### ISSUE THREAD

**Issue by scriptxd** [jfadev/bottok#4]
proot-distro alpine 

dlopen failed: library "libpthread.so.0" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/tls_client/dependencies/tls-client-arm64.so in namespace (default)
localhost:~/TikTok-ViewBot# --add-binary '{/data/data/
com.termux/files/usr/lib/python3.11/site-packages}/tls
_client/dependencies/tls-client-amd64.so:tls_client/de
pendencies'
Please help....

**Comment by jfadev** [comment]
Look at this: https://stackoverflow.com/questions/53936680/java-lang-unsatisfiedlinkerror-dlopen-failed-library-libpthread-so-0-not-fou

"localhost:~/TikTok-ViewBot" looks like it is trying to run a different script than this one.

**Comment by scriptxd** [comment]
Thanks...Whats Happened With zefoy sending only 1-7 views per submit
