### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by tacchiinii** [jfadev/bottok#49]
![Bildschirmfoto vom 2024-02-09 22-56-31](https://github.com/jfadev/bottok/assets/159579434/5cbf30a1-8f42-4475-86e5-441ac287058a)

I've tried it multiple times (ubuntu) and I get the same error each time

**Comment by jfadev** [comment]
That error is because you are using node lower than version 18. BotTok needs Nodejs >= 18

**Comment by tacchiinii** [comment]
yeah i fixed it at night. Everything works! Thats why i closed the issue again. But thx for your reply
