### ISSUE TITLE
Add freer.es support

### ISSUE THREAD

**Issue by scriptxd** [jfadev/bottok#5]
Cookies Expired Quickly...
Add unlimited cookies system
 "Termux" 

Also an error  
After Cookies Expire
![Screenshot_2023_0304_180424](https://user-images.githubusercontent.com/104721718/222900129-c3b9d32b-ddf4-4b51-a83b-26e235323b99.jpg)

 https://freer.es/ Available ?

**Comment by jfadev** [comment]
I checked the site and it doesn't seem to have anything for TikTok.

**Comment by scriptxd** [comment]
![Screenshot_20230307_233100](https://user-images.githubusercontent.com/104721718/223502146-f8ef33a6-8cdb-4e32-baa7-b1402e77ef64.jpg)
Views Available...

**Comment by scriptxd** [comment]
🙃....Bro...❤️ 

Bro Mass Botting .....✌️🔥

Good Luck.....

**Comment by shaiigon** [comment]
what does it do?

**Comment by jfadev** [comment]
Freer support rejected for having the same view provider etc. as zefoy.

**Comment by jfadev** [comment]
Freer.es support has been added to this version: 
https://github.com/jfadev/bottok/releases/tag/v1.1.0
