### ISSUE TITLE
error not start 

### ISSUE THREAD

**Issue by CodingBDX** [jfadev/bottok#63]
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by CodingBDX** [comment]
ok i update node to 18 with volta
but i don't know if i work i try our code for video, it's lunch bottok and that all...nothing appear

and have ou csv for example, i try to paste but not work

**Comment by CodingBDX** [comment]
nothing happend

./multi-task.sh '/home/anto/Documents/test.csv' 
BotTok 1.1.4 TikTok Up Bot (by @jfadev)

 You are using the FREE version!
 The --detach or -d mode is exclusive to Premium mode
 and allows BotTok to be launched as background processes.
 💳 Buy license in https://bit.ly/bottok-premium

**Comment by jfadev** [comment]
That's not a bug. You need a premium license to use that feature.
