### ISSUE TITLE
few issue please help

### ISSUE THREAD

**Issue by Lioness02** [jfadev/bottok#8]
1: captcha not solving automaticlly just says zefoy c 2023 in image also.
have to manually type the captcha in pop up browser or sometimes i can  look at the pop up browser captcha and enter in the cmd.

i have premium account how come i still see count down.
also why does it fail to submit and gives error and button for views become disable.

**Comment by jfadev** [comment]
Fixed in https://github.com/jfadev/bottok/commit/386e04c7ee02f6c62c1c47d33f643539c8f3fb56
